trigger:
  branches:
    exclude:
      - '*'

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    git clone https://albjujbujty77fddryyy27n322h7qyn376wjwlo4l24s5pjlmknq@dev.azure.com/GFTAZ/GCP%20Cloud%20Practice%20Initiative/_git/sandboxscheduler
    $(System.DefaultWorkingDirectory)/terraform
  displayName: 'Clone pipeline_yaml repository'

- script: |
    cd $(System.DefaultWorkingDirectory)/terraform
    echo "$(terraformAuthFile.secureFilePath)"
    terraform init -backend-config="bucket=sandboxtfstate" -backend-config="prefix=sanboxpolicy"
    terraform plan -var="project_id=kayprjct01-358115" -out=tfplan
  displayName: 'Terraform Init and Plan'

- script: |
    cd $(System.DefaultWorkingDirectory)/pipeline_yaml
    terraform apply -auto-approve tfplan
  displayName: 'Terraform Apply'

- task: PublishPipelineArtifact@1
  displayName: 'Publish Terraform state'
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/terraform.tfstate'
    artifactName: 'terraform-state'
