trigger:
  branches:
    exclude:
      - '*'

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- task: DownloadSecureFile@1
  name: terraformAuthFile
  displayName: 'Download Terraform authentication file'
  inputs:
    secureFile: 'kayprjct01-358115-169da30b83f0.json'

- script: |
    echo "$(terraformAuthFile.secureFilePath)"
    terraform init -backend-config="bucket=sandboxtfstate" -backend-config="prefix=sanboxpolicy"
    terraform plan -var="project_id=kayprjct01-358115" -out=tfplan
  displayName: 'Terraform Init and Plan'

- script: |
    terraform apply -auto-approve tfplan
  displayName: 'Terraform Apply'

- task: PublishPipelineArtifact@1
  displayName: 'Publish Terraform state'
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/terraform.tfstate'
    artifactName: 'terraform-state'
